#!/usr/bin/env python3
import os
import sys
import time


method = os.environ.get("REQUEST_METHOD", "N/A")
query_string = os.environ.get("QUERY_STRING", "N/A")
incoming_http_cookie = os.environ.get("HTTP_COOKIE", "None found") 
content_length = os.environ.get("CONTENT_LENGTH")
post_body = ""

server_set_cookie = os.environ.get("SERVER_SET_COOKIE", "") 

if content_length and content_length.isdigit() and int(content_length) > 0:
    try:
        post_body = sys.stdin.read(int(content_length))
    except Exception as e:
        post_body = f"ERROR READING BODY: {e}"

new_visit_timestamp = int(time.time())
cookie_attributes = f"Max-Age=3600; Path=/; HttpOnly" 

sys.stdout.write("Content-Type: text/plain\r\n")

if server_set_cookie:
    sys.stdout.write(server_set_cookie)

sys.stdout.write(f"Set-Cookie: LastVisit={new_visit_timestamp}; {cookie_attributes}\r\n")

sys.stdout.write("\r\n")

sys.stdout.write(f"--- COOKIE TEST RESULTS ---\n")
sys.stdout.write(f"1. **NEW Set-Cookie Value (Generated by Script):** LastVisit={new_visit_timestamp}\n")
sys.stdout.write(f"2. **INCOMING Cookie (Received from Browser):** {incoming_http_cookie}\n")
sys.stdout.write(f"3. **Server Set-Cookie (from C++):** {server_set_cookie.strip()}\n")
sys.stdout.write(f"4. Request Method: {method}\n")
sys.stdout.write(f"5. Query String: {query_string}\n")
sys.stdout.write(f"6. Body Data Read: {post_body[:50]}...\n")
sys.stdout.write(f"--- END TEST ---\n")