print("Content-Type: text/html\r\n")
print("\r\n")

print("<!DOCTYPE html>")
print("<html>")
print("<head><title>Hello</title></head>")
print("<body>")
print("<h1>HELLO WORLD</h1>")
print("</body>")
print("</html>")